name: Setup

runs:
  using: composite
  steps:
    - name: 'Check out the repo'
      uses: 'actions/checkout@v3'
    - name: 'Install Node.js'
      uses: 'actions/setup-node@v3'
      with:
        cache: 'yarn'
        node-version: 20
    - name: 'Install the dependencies'
      shell: bash
      run: 'yarn install --frozen-lockfile'