name: Release
on:
  push:
    branches:
      - release-*
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: Which package to release
        options: 
          - "contracts"
          - "configs"

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions: {} #reset

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn install
      - run: bash scripts/git-user-config.sh
      
  start:
    runs-on: ubuntu-latest
    name: Start Release Candidate
    ## Run this job only if Manually triggered by the user on UI of main branch.
    if: ${{ github.ref_name == 'main' && github.event_name == 'workflow_dispatch' }}
  - name: Create Release Candidate Branch
    run: bash scripts/start.sh
    env:
      PACKAGE: ${{ github.event.inputs.package }}
  - name: Re-run workflow
    with:
      script: |
        github.rest.actions.createWorkflowDispatch({
          owner: github.repository_owner,
          repo: github.repository,
          workflow_id: 'release-cycle.yml',
          ref: steps.start.outputs.branch,
        });